---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service-cb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-service-app
      version: "1.0"
  template:
    metadata:
      name: rest-service-pod
      labels:
        app: rest-service-app
        version: "1.0"
    spec:
      containers:
      - name: rest-service-container
        image: mtorne/restservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: rest-service-svc
  labels:
    app: rest-service-app
spec:
  selector:
    app: rest-service-app
    version: "1.0"
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80