---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restservice-cb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-service-app
      version: 1
  template:
    metadata:
      name: rest-service-pod
      labels:
        app: rest-service-app
        version: 1
    spec:
      containers:
      - name: rest-service-container
        image: mtorne/restservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: rest-service-svc
  labels:
    app: rest-service-app
spec:
  selector:
    app: rest-service-app
    version: 1
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80